---
title: "Analysis of Toronto Marriage on Time Base"
author: 
  - Bell He
thanks: "Code and data are available at: https://github.com/iJustinn/Demonstration_Exercise."
date: 19 September 2024
date-format: long
abstract: |
  This document presents an analysis of marriage license statistics in Toronto recoded with time
  The analysis includes a time series graph of marriage licenses issued over time, grouped by civic center.
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)

data <- read_csv(here::here("data/analysis_data/analysis_data.csv"))

```


# Introduction

You can and should cross-reference sections and sub-sections. We use @talia, @opendatatorotno, and @rohan.

The remainder of this paper is structured as follows. @sec-mydatasection



# Data {#sec-mydatasection}

Some of our data is of penguins (@fig-marriage), from @palmerpenguins.

```{r}
#| label: fig-marriage
#| fig-cap: Bills of penguins
#| echo: false

data |> 
  ggplot(aes(x = date, y = marriage_licenses)) +
  geom_point()

```
